### ISSUE TITLE
List/Update Sales - Filter view should be default view instead of blank screen.

### ISSUE THREAD

**Issue by gkyx** [ibrahimseckin/ErkoSMS#30]
It can be changed to "Search sales" rather than filter sales. Helpful message can be given. E.g. "Enter search criteria to view sales data"

**Comment by arielortega23** [comment]
filter is removed from the view

**Comment by gkyx** [comment]
Blank screen issue still exists, it can show the open sales by default. I assume most of the time "open sales" screen will be used. We might as well load it directly instead of showing a blank screen and wait for an unnecessary click.

**Comment by erolcanozgen** [comment]
as default active orders will be shown.
